14 add consideration for architecture to install correct tracer for x86 and arm (#18)
* dynamic installation based on os and architecture

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -31,7 +31,11 @@ jobs:
       run: echo "test"
 
   test-fastci-action:
-    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        os: [ubuntu-latest, windows-latest]
+        arch: [amd, arm]
+    runs-on: ${{ matrix.os }}
     steps:
     - name: Checkout repository
       uses: actions/checkout@v3
@@ -42,6 +46,14 @@ jobs:
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         fastci_otel_token: ${{ secrets.FASTCI_OTEL_TOKEN }}
+    - name: Check tracer process
+      if: matrix.os == 'ubuntu-latest'
+      run: |
+        if pgrep -f tracer; then
+          echo "Tracer process found."
+        else
+          echo "Tracer process NOT found!" && exit 1
+        fi
     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
