cache load and save

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -26,7 +26,42 @@ jobs:
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         fastci_otel_token: ${{ secrets.FASTCI_OTEL_TOKEN }}
+
+  test-fastci-action:
+    strategy:
+      matrix:
+        arch: [amd, arm]
     
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
+    - name: Run FastCI Action
+      uses: ./
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        fastci_otel_token: ${{ secrets.FASTCI_OTEL_TOKEN }}
+    - name: Check tracer process
+      run: |
+        uname -a
+        if pgrep -f tracer; then
+          echo "Tracer process found."
+        else
+          echo "Tracer process NOT found!" && exit 1
+        fi
+    - name: Setup Node.js
+      uses: actions/setup-node@v3
+      with:
+        node-version: '20'
+        cache: 'npm'
+    - name: Simulate files marked for upload
+      run: |
+        mkdir -p /tmp/fastci/cache/upload
+        mkdir -p /tmp/test
+        echo "hello" > /tmp/test/hello.txt
+        ln -s /tmp/test /tmp/fastci/cache/upload/t1
 
   check-tmp-test-exists:
     needs: test-fastci-action
@@ -58,41 +93,7 @@ jobs:
             echo "/tmp/test does NOT exist!" && exit 1
           fi
 
-  test-fastci-action:
-    strategy:
-      matrix:
-        arch: [amd, arm]
-    
-    runs-on: ${{ matrix.os }}
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
-    - name: Run FastCI Action
-      uses: ./
-      with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        fastci_otel_token: ${{ secrets.FASTCI_OTEL_TOKEN }}
-    - name: Check tracer process
-      run: |
-        uname -a
-        if pgrep -f tracer; then
-          echo "Tracer process found."
-        else
-          echo "Tracer process NOT found!" && exit 1
-        fi
-    - name: Setup Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: '20'
-        cache: 'npm'
-    - name: Simulate files marked for upload
-      run: |
-        mkdir -p /tmp/fastci/cache/upload
-        mkdir -p /tmp/test
-        echo "hello" > /tmp/test/hello.txt
-        ln -s /tmp/test /tmp/fastci/cache/upload/t1
+
 
   test-and-build:
     runs-on: ubuntu-latest
