fix tracer not found

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -47,13 +47,13 @@ jobs:
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         fastci_otel_token: ${{ secrets.FASTCI_OTEL_TOKEN }}
-    - name: Check tracer process
+    - name: Check agent process
       if: matrix.os == 'ubuntu-latest'
       run: |
-        if pgrep -f tracer; then
-          echo "Tracer process found."
+        if pgrep -f agent; then
+          echo "agent process found."
         else
-          echo "Tracer process NOT found!" && exit 1
+          echo "agent process NOT found!" && exit 1
         fi
     - name: Setup Node.js
       uses: actions/setup-node@v3
