fix

diff --git a/.github/workflows/promote-tag.yml b/.github/workflows/promote-tag.yml
--- a/.github/workflows/promote-tag.yml
+++ b/.github/workflows/promote-tag.yml
@@ -2,7 +2,17 @@ name: Promote Tag to Latest Release
 
 on:
   workflow_dispatch:
-  push:
+    inputs:
+      tag_to_update:
+        description: "Select the signed tag to update."
+        required: true
+        type: choice
+        options:
+          - v0
+      release_tag:
+        description: "The full tag version (e.g., release/v1.2.3)."
+        required: true
+        type: string
 
 jobs:
   promote-tag:
@@ -13,14 +23,15 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Get latest release tag
-        id: get_latest_release
+      - name: Check if provided release_tag exists
         run: |
-          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
-          echo "latest_tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"
+          if ! git rev-parse "refs/tags/${{ inputs.release_tag }}" >/dev/null 2>&1; then
+            echo "Error: Tag '${{ inputs.release_tag }}' does not exist."
+            exit 1
+          fi
 
-      - name: Move v0 tag to latest release
+      - name: Move ${{ inputs.tag_to_update }} tag to ${{ inputs.release_tag }}
         run: |
-          git tag -f v0 ${{ steps.get_latest_release.outputs.latest_tag }}
-          git push origin v0 --force
+          git tag -f ${{ inputs.tag_to_update }} ${{ inputs.release_tag }}
+          git push origin ${{ inputs.tag_to_update }} --force
 
